# Generated by Django 3.0.6 on 2020-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='django react'),
            preserve_default=False,
        ),
    ]
